### PR TITLE
Avoid making slices from nil slices on copy

### PR DESCRIPTION
**Pull request by acruikshank**
## Problem

When hamt Pointers are created they are initialized with a nil KVs slice. When we copy, we always make a new KVs slice and copy the old values into it if there are any. This means that the original and copy are very slightly different if no KVs are added to the pointer. This means you can't use a hash to determine if the copy and original are equal.

## Solution

Check if the slice is nil. If so, don't make a new one.

### CODE REVIEW

**Comment by clkunzang** [comment]
Does this also need to handle the case in which the KVs slice is empty rather than nil?

**Comment by acruikshank** [comment]
@clkunzang The case where the KVs slice is empty was already working and should continue working.

**Comment by whyrusleeping** [comment]
hrm... this feels hacky, but it makes sense. This makes a copy pass a deep equality check, whereas it didnt before.

lemme grab a review from some random internet stranger, then we can merge. cc @warpfork

**Comment by warpfork** [comment]
Would be nice if there was a test that aimed at the equality case around those nil slices specifically.  The test that nil'ness is preserved is good, but sort of doesn't explain the "why" of itself.

**Comment by dignifiedquire** [comment]
@acruikshank @Stebalien @whyrusleeping any update here?

**Pull request merged**
