### PR TITLE
Fix deletion

### PR DESCRIPTION
**Pull request by ianopolous**

### CODE REVIEW

**Comment by ianopolous** [comment]
During this I also discovered that the hash function we are using maps keys with the same prefix to hashes with the same prefix, which will result in deeper trees than required with a better hash function.

**Comment by Kubuxu** [comment]
We were using murmur3 in case of HAMT in pb-unixfs

**Comment by Kubuxu** [comment]
Could you gofmt the files?

**Comment by Kubuxu** [comment]
I can also confirm that it fixes the issue, I've started fuzzing the go-hamt-ipld and this was one of the first thing that came up.

**Pull request merged**
